version: "3.8"

services:
  db:
    image: mysql:8
    volumes:
      - ./dbdata:/var/lib/mysql
    env_file: .env

  pma:
    image: phpmyadmin:latest
    ports:
      - "8800:80"
    env_file: .env
